[package]
name = "sha1lz4"
version = "1.0.1"
edition = "2024"

[dependencies]
clap = "4.5.38"
clio = { version = "0.3.5", features = ["clap-parse"] }
itertools = "0.14.0"
lz4_flex = { version = "0.11.3", features = ["frame"] }
sha1 = "0.10.6"
